### ISSUE TITLE
Error with golang 1.17+ / Trick to build with golang 1.16

### ISSUE THREAD

**Issue by xi-ao** [opencoff/go-tunnel#7]
Just a tiny trick. If you're on an environment where only Go 1.17+ is available, you might encounter the following error when running the built binary:

```shell
$ ./bin/linux-amd64/gotun
panic: qtls.CertificateRequestInfo doesn't match

goroutine 1 [running]:
github.com/marten-seemann/qtls-go1-16.init.0()
```

In this case, you may want to use this oneliner to build the binary in a temporary Docker container with Go 1.16:

```shell
docker run --rm -v $(pwd):/build -w /build -u $(id -u):$(id -g) -e HOME=/build golang:1.16 make
```

So then:
```shell
$ ./bin/linux-amd64/gotun
./bin/linux-amd64/gotun: No config file!
Usage: ./bin/linux-amd64/gotun [options] config-file
```

**Comment by opencoff** [comment]
Thanks for the note. The correct fix is to update go.mod with the latest upstream dependency for quic-go and its dependents.

I just did exactly that and now, go-tunnel compiles & runs correctly on golang 1.17
